# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rsegul_wrappers", use_symbols = TRUE, package_name = "rsegul")

#' @docType package
#' @usage NULL
#' @useDynLib rsegul, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
is_dna <- function(string) .Call(wrap__is_dna, string)


# nolint end
